---
- hosts: all
  sudo: True
  vars_files:
    - ~/Projects/ansible/vars/defaults.yml
    - vars.yml
  tasks:
   - name: yum | virtualenv | install
     yum: name=python-virtualenv state=installed

   - name: yum | gcc | install
     yum: name=gcc state=installed

   - name: project | root | create
     file: path={{ project.root }} state=directory owner=nginx group=nginx

   - name: project | checkout
     git: >
       repo={{ project.repo }}
       dest={{ project.root }}/src
     sudo_user: nginx

   - name: project | root | check permissions
     file:
       path: "{{ project.root }}"
       state: directory
       recurse: yes
       owner: nginx
       group: nginx

   - name: pip | install
     pip: >
       virtualenv={{ virtualenv }}
       requirements={{ project.root }}/src/requirements.txt
     sudo_user: nginx

   - name: project | hyde | generate
     shell: 
       "{{ virtualenv }}/bin/hyde gen -d {{ project.root }}/html"
     args:
       chdir: "{{ project.root }}/src"
